### ISSUE TITLE
when new samples from an existing donor are uploaded, old samples join the new project

### ISSUE THREAD

**Issue by klearned** [BD2KGenomics/dcc-spinnaker-client#38]
Uploading new samples from a donor that already exists in the system (e.g. I've uploaded other samples from the donor in a different project in the past), causes samples previously uploaded from that donor to join the new project. And, at least in one case that I checked, the previously uploaded samples are no longer available in their original project.

This is very confusing to the user.

This has happened in the last three uploads I've done.

**Comment by klearned** [comment]
@wshands @caaespin

**Comment by klearned** [comment]
I have now also seen cases where the new samples (if other samples from the same donor have been uploaded in past projects) jump to old projects to be with the other samples from their donor.

I suspect these are two symptoms of the same bug: sometimes the new samples go to an old project and sometimes the old samples jump to the new project. Either way, the samples from the same donor seem to be trying to stay together regardless of their project.

**Comment by wshands** [comment]
The way our metadata is structured now the Submitter Donor ID is at the same level as Project. So you can't have samples from the same Donor in different projects. The workaround is to use a different Submitter Donor ID for the samples  you want in a different project, maybe just concatenate the Submitter Donor ID for those samples with a suffix so that this will work but you can still identify them as coming from the same donor.
This anomaly will probably not be fixed soon because it would require a metadata schema change and there are some other tasks ahead of this in the priority list.

**Comment by klearned** [comment]
For Treehouse, I think the best workaround is to put the Submitter Specimen ID in the Donor Id field. So, Submitter Specimen Id = Submitter Sample Id = Submitter Donor Id for Treehouse.
